# Generated by Django 6.0.2 on 2026-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, choices=[('2ndeA', '2nde A'), ('2ndeC', '2nde C'), ('1ereA', '1ère A'), ('1ereC', '1ère C'), ('1ereD', '1ère D'), ('TleA', 'Terminale A'), ('TleC', 'Terminale C'), ('TleD', 'Terminale D'), ('L1_INFO', 'Licence 1 Informatique'), ('L2_INFO', 'Licence 2 Informatique'), ('L3_INFO', 'Licence 3 Informatique')], max_length=20),
        ),
    ]
